"""Module 07 - Middleware and CORS.

Middleware registration order is the thing to pay attention to in this file.
Starlette wraps the application from the inside out, so the LAST middleware
added is the OUTERMOST layer - the first to see a request and the last to touch
a response. Registering in the wrong order produces bugs that are entirely
invisible in the code.
"""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware

from config import get_settings
from context import get_request_id
from handlers import handle_unexpected_error, register_error_handlers
from logging_config import setup_logging
from middleware import (
    REQUEST_ID_HEADER,
    RESPONSE_TIME_HEADER,
    RequestContextMiddleware,
    add_security_headers_middleware,
)
from routers import products
from schemas import ERROR_RESPONSES

settings = get_settings()
setup_logging(settings.log_level)
logger = logging.getLogger("api.lifespan")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run once on startup and once on shutdown.

    Everything before the yield runs at startup, everything after runs at
    shutdown. This replaces the deprecated @app.on_event("startup") decorators
    and is better because setup and its matching teardown sit next to each
    other rather than in two unrelated functions.

    This is where a database connection pool is opened in module 11 and where
    an HTTP client is created in module 10.
    """
    logger.info("startup: %s in %s mode", settings.app_name, settings.environment)
    logger.info("startup: cors origins %s", settings.allowed_origins or "(none configured)")
    yield
    logger.info("shutdown: releasing resources")


app = FastAPI(
    title="Observable API",
    description="Module 07 of the FastAPI learning journey - middleware, CORS and lifespan.",
    version="0.1.0",
    lifespan=lifespan,
    responses=ERROR_RESPONSES,
)

register_error_handlers(app)

# --- middleware, registered innermost first ---

# 1. Innermost. Compresses the body after everything else has finished with it.
#    Compressing first and then editing headers would be the wrong order.
app.add_middleware(GZipMiddleware, minimum_size=settings.gzip_minimum_size)

# 2. Request id, timing, access log, and the catch-all for unhandled exceptions.
#    on_unhandled is what keeps a 500 inside the middleware stack; see the class
#    docstring for why Starlette's own handling is not sufficient here.
app.add_middleware(RequestContextMiddleware, on_unhandled=handle_unexpected_error)

# 3. Static security headers, using the decorator form. Registered outside the
#    request context middleware so that the error responses it produces are
#    decorated too.
add_security_headers_middleware(app)

# 4. Outermost, added last. CORS must be the outermost user middleware so that
#    responses generated by anything inside it - including error responses -
#    still get their CORS headers. A browser cannot read a response missing
#    those headers, so a 500 without them shows up in the console as an opaque
#    CORS failure and the real error is invisible.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type", REQUEST_ID_HEADER],
    # Without expose_headers, browser JavaScript can only read a small fixed
    # set of response headers. Our two custom headers would be present on the
    # wire, visible in devtools, and unreadable from fetch(). This one line is
    # the difference.
    expose_headers=[REQUEST_ID_HEADER, RESPONSE_TIME_HEADER],
    max_age=600,
)

app.include_router(products.router)


@app.get("/health", tags=["general"], summary="Service health check")
def health_check() -> dict[str, str]:
    """Report that the service is running."""
    return {
        "status": "ok",
        "version": app.version,
        "environment": settings.environment,
        "request_id": get_request_id(),
    }
